llm:
  type: openai
  base_url: http://localhost:11434/v1
  model: deepseek-coder:1.3b

probes:
  - promptinjection
  - jailbreak
  - sensitiveinfo
  - sqlinjection
  - codeexecution

output:
  format: text
  file: garak_results.txt

run:
  parallel_probes: 2
  max_generations: 5

