obj-m += vulnerable_module.o

all:
        make -C /lib/modules/\<span class="math-inline">\(shell uname \-r\)/build M\=\\$\(PWD\) modules
clean\:
make \-C /lib/modules/\\$\(shell uname \-r\)/build M\=\\</span>(PWD) clean
